"""add_sync_status

Revision ID: 08273d3954f1
Revises: 5979360d6b8b
Create Date: 2026-04-16 21:34:02.553901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08273d3954f1'
down_revision: Union[str, Sequence[str], None] = '5979360d6b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'sync_status',
            sa.String(length=32),
            nullable=False,
            server_default='IDLE',
        ),
    )
    op.add_column('users', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'sync_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_synced_at')
    op.drop_column('users', 'sync_status')
    # ### end Alembic commands ###
