"""add_spotify_id

Revision ID: 5979360d6b8b
Revises: ebf7f85d04fa
Create Date: 2026-04-10 10:50:08.062553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5979360d6b8b'
down_revision: Union[str, Sequence[str], None] = 'ebf7f85d04fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_spotify_id'), 'users', ['spotify_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_spotify_id'), table_name='users')
    op.drop_column('users', 'spotify_id')
    # ### end Alembic commands ###
