"""add_vector_embedding

Revision ID: ebf7f85d04fa
Revises: f32cc46b6a61
Create Date: 2026-04-05 19:48:10.628487

"""

from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebf7f85d04fa"
down_revision: Union[str, Sequence[str], None] = "f32cc46b6a61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.add_column("tracks", sa.Column("embedding", Vector(384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracks", "embedding")
    # ### end Alembic commands ###
