"""add_audio_features

Revision ID: f32cc46b6a61
Revises: 2f1eaa6d7a39
Create Date: 2026-04-01 17:23:58.301221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f32cc46b6a61'
down_revision: Union[str, Sequence[str], None] = '2f1eaa6d7a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('bpm', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('energy', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('valence', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('danceability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'danceability')
    op.drop_column('tracks', 'valence')
    op.drop_column('tracks', 'energy')
    op.drop_column('tracks', 'bpm')
    # ### end Alembic commands ###
